
auto: true
pygments: true


title : Internal Structure
tagline: Tagline
author :
  name : Stuart Andrews
  email : blah@email.test
  github : tub78
  twitter : tub78
  feedburner : feedname

analytics :
  provider : google 
  google : 
    tracking_id : 'UA-2216067-4'

comments :
  provider : disqus
  disqus :
    short_name : 'istructure'

markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'fenced_code', 'tables', 'strikethrough', 'lax_htmlblock', 'no_intraemphasis']

# Github defaults ['fenced_code', 'tables', 'strikethrough', 'lax_htmlblock', 'gh_blockcode']
# Github comment defaults ['fenced_code', 'tables', 'strikethrough', 'lax_htmlblock', 'gh_blockcode', 'hard_wrap', 'autolink]'

# extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'space_after_headers', 'superscript']
# render_options: ['filter_html', 'with_toc_data']

# markdown: rdiscount
# rdiscount:
#   extensions:


exclude: [ 'vendor'
            ]
